title: "Latin America Population Age Structure Dataset"
description: "Demographic dataset: Population age structure in Latin America (11 countries, 2000-2023). Static microsite with 907 pages. DOI: 10.17632/ygkmshr5fv.1"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/latin-america-population-age-structure-dataset"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
social:
  name: Juan Moisés de la Serna Tuya
  links:
    - https://orcid.org/0000-0002-8401-8018
    - https://juanmoisesdelaserna.es
    - https://github.com/juanmoisesd
doi: 10.17632/ygkmshr5fv.1
show_excerpts: true
